<?php
namespace app\admin\controller;

use app\admin\service\IndexService;
use think\facade\Lang;
use think\facade\Session;
use think\Request;
use SC;

class IndexController extends BaseController
{
    // 是否批量验证
    protected $batchValidate = true;

    public function initialize()
    {
//        dump($_SERVER);
//        echo dirname($_SERVER['SCRIPT_NAME']) . '/static';
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function login(Request $request)
    {

        if ($request->isPost()) {
            $index = new IndexService();
            $postData = [
                'username' => $request->param('username'),
                'password' => $request->param('password'),
                'verify' => $request->param('verify'),
            ];
            $validateRes = $this->validate($postData, 'app\admin\validate\loginValidate');
            if ($validateRes !== true) {
                return $this->ajaxReturnFail($validateRes, false, ['scene' => 'verify']);
            }
            $is_login = $index->login($postData['username'], $postData['password']);

            return $this->ajaxReturnSuccess($is_login);
        }
        return $this->fetch();
    }

    public function index()
    {
        $this->setTitle(Lang::get('shop_index_title'));
        return $this->fetch();
    }

}
